language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgresql

script: bundle exec rspec spec

# Set up database
before_script:
  - psql -c 'create database rails-fun_test;' -U postgres.
  - bundle exec rake db:migrate
